---
title: "Uwalaka_Chiagozie_Lab2"
output:
  html_document:
    df_print: paged
---

```{r}
#install.packages('faraway')
#install.packages("lsr") #used to obtain standardcoef function
library('faraway')
data(stat500)
library("lsr")
# install.packages('confintr')
library("confintr")
# install.packages("EnvStats") used to find single varience test
library(EnvStats)
```

Problem 1: 
```{r}
x.bar <- mean(stat500$total)
y.bar <- mean(stat500$final)
SXY <- sum((stat500$final-x.bar)*(stat500$total-y.bar))
SXX <- sum((stat500$final-x.bar)^2) 

```


```{r}
# A
stat500.corr<-cor(stat500)
#B
plot(stat500$total, stat500$final) # it seems like the correlation is positive.

#C
attach(stat500)
model<-lm(total~final)
SSE <- sum((model$residuals)^2) # Sum sqaured error
MSE <- SSE/(55-2)
res.se <- sqrt(MSE) #standard error of residuals
var.beta1 <- res.se^2/SXX 
se.beta1 <- sqrt(var.beta1)
summary(model)
# standardCoefs(model) # extract standardized beta coefficient
beta1 <- SXY/SXX #beta.1
beta0 <- y.bar - beta1*x.bar 
beta0
beta1
pred <- predict(model, se=TRUE, interval="prediction")

pred


```


Problem 2 
```{r}
library(readxl)
N_data<-read_excel("data-table-B1.xls")
data<-data.frame(N_data)
attach(data)
# A
model2<- lm(y~x8, as.data.frame(data))
model2
# B
anova(model2)
summary(model2)
#C
confint(model2,'x8',level=0.95)
#E
ci_mean(data[data$x8<=2000, "y"])

```
Problem 3
```{r}
Hours<-c(159,224,222,149,
         280,379,362,260,
         101,179,168,485,
         212,264,250,170)

#A
hist(Hours)
# Ho>225
# Ha<=225

#B
t.test(Hours, y=NULL, "less", mu=225)
# We can conclude that the hypothesis is inaccurate and the mean is not less than 225.

#C
t=0.66852 # found from t.test
length(Hours)
mean(pt(t, 16))
# p-value=.743341 as seen in the t-test

#D
ci_mean(Hours) # confidence interval is (188.8927, 294.1073) with a margin of error of 52.6073.

#E
# Ho: sigma_sq>9000
# Ha: sigma_sq<=9000SS

varTest(Hours, alternative = "greater", conf.level = .95, sigma.squared = 9000)
# We do not reject the hypothesis since the varience is greater than 9000
```

