---
title: "Uwalaka_Lab 8"
output:
  word_document: default
  html_notebook: default
---

Problem 1
```{r}
#Creating the data
test <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)

target_speed <- c(400, 220, 490, 210, 500, 270, 200, 470, 480, 310, 240, 490, 420, 330, 280, 210, 300, 470, 230, 430, 460, 220, 250, 200, 390)

y <- c(0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0)

missile <- cbind(test, target_speed, y)
missile <- as.data.frame(missile)
head(missile)
```

```{r}
#A
model<- glm(y~. , data=missile, family=binomial(link="logit"))
summary(model)
model.red<-step(model)
linear.pred <- model$linear.predictors
head(linear.pred)


#B
model$null.deviance
deviance(model)
model$deviance
deviance(model.red)
# Compared to the reduced model deviance of 20.3636, the original model has a better fit with a deviance of 20.11 or 20.10564.

#C
model$coefficients # beta 1 = .04109817 is positive which increase the chances of the missle being a hit.

# D
QuadMod<- glm(y~I(target_speed)+I(target_speed^2),family=binomial(link = "logit"))
summary(QuadMod) # Since the p-value corresponding target_speed is greater than 0.05 so there is insignificant evidence that this quadratic term is need for the model.

```

Problem 2
```{r}
#Creating the data
income <- c(45000, 40000, 60000, 50000, 55000, 50000, 35000, 65000, 53000, 48000, 37000, 31000, 40000, 75000, 43000, 49000, 37500, 71000, 34000, 27000)

age <- c(2, 4, 3, 2, 2, 5, 7, 2, 2, 1, 5, 7, 4, 2, 9, 2, 4, 1, 5, 6)

y <- c(0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0)

auto_purchase <- cbind(income, age, y)
auto_purchase <- as.data.frame(auto_purchase)
head(auto_purchase)
```

```{r}
# A
model.2<-glm(y~income+age,family=binomial(link=logit),auto_purchase)
summary(model.2)
#B
model.2$deviance

#C
model.2$coefficients
#Both B1=7.381679e-05 and B2=9.878861e-01 are positive so they have positive impact on the puchasing probability of the car.
#D
beta=model.2$coefficients 
beta=as.vector(beta) # eta=B0+B1*45000+B2*5 eta=c(1,45000,5)%*%beta # 1 is for coefficient of B0 eta prob=exp(eta)/(1+exp(eta)) 
beta 
eta=c(1,45000,5)%*%beta
prob=exp(eta)/(1+exp(eta)) # The probability of purchasing vehicle of the family with income=$45000 and old vehicle age=5 years in 6 months is 0.77102795.

#E
model.3=glm(y~income+age+income:age,family=binomial(link=logit),auto_purchase)
summary(model.3)
# It is not required to add the interaction term because the original x1:x2 is not that significant also after adding the interaction term we can see that the significance level the original x1 and x2 is increased which is not a good sign.

#G
#statistics for income
summary(income)
sd(income)
#Statistics for age
summary(age)
sd(age)

#F
# 95% confidence interval for income
confint(model.3, 'income', level=0.95)
## The 95% confidence interval for the parameter income is [-0.0004675, 0.000108435]


# 95% confidence interval for age 
confint(model.3, "age", .95)
# The 95% confidence interval for the parameter age is [-7.6507362, 0.9722156]
```
Problem 3
```{r}
library(wooldridge)
data("alcohol")
attach(alcohol)
#A
model.4<-glm(abuse~.,family=binomial(link=logit),alcohol)
summary(model.3)

#B
model.red.2<-step(model.4)
summary(model.red.2)

#C
newdata<-data.frame(fathalc=1, mothalc=1, centcity=1, abuse=mean(abuse), status=mean(status), unemrate=mean(unemrate), age=mean(age), educ=mean(educ), married=mean(married), famsize=mean(famsize), white=mean(white), exhealth=mean(exhealth), vghealth=mean(vghealth), goodhealth=mean(goodhealth), fairhealth=mean(fairhealth), northeast=mean(northeast), midwest=mean(midwest), south=mean(south), centcity=mean(centcity), outercity=mean(outercity), qrt1=mean(qrt1), qrt2=mean(qrt2), qrt3=mean(qrt3), beertax=mean(beertax), cigtax=mean(cigtax), ethanol=mean(ethanol), livealc=mean(livealc), inwf=mean(inwf),employ=mean(employ), agesq=mean(agesq), beertaxsq=mean(beertaxsq), cigtaxsq=mean(cigtaxsq), ethanolsq=mean(ethanolsq), educsq=mean(educsq))

pred <- predict(model.red.2, newdata, se=TRUE, interval="prediction")


```

